In [50]:
import torch
import numpy as np


In [51]:
print(torch.cuda.is_available())
print(torch.__version__)

False
2.6.0+cpu


In [52]:
W = torch.tensor([[1,2],[3,4]])
X = torch.tensor([[1,2],[3,4]])
Y = torch.tensor([[1,2],[3,4]])
W, X, Y

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [53]:
w = torch.empty(2,3) # 创建一个2行3列的矩阵，元素值随机
x = torch.zeros(2,3) # 创建一个2行3列的矩阵，元素值为0
y = torch.ones(2,3) # 创建一个2行3列的矩阵，元素值为1
w, x, y

(tensor([[-3.7160e+27,  8.3798e-43,  1.8750e+00],
         [ 1.8750e+00,  1.8750e+00,  0.0000e+00]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [54]:
w = torch.rand(3,3) # 创建一个3行3列的矩阵，元素值随机
print(w)
w = torch.randn(3,3) # 创建一个3行3列的矩阵，元素值随机，服从标准正态分布
print(w)
w = torch.randint(1,10,(3,3)) # 创建一个3行3列的矩阵，元素值随机，范围1-10
print(w)

tensor([[0.4675, 0.2468, 0.1525],
        [0.4027, 0.5047, 0.5172],
        [0.7172, 0.5239, 0.6089]])
tensor([[-0.1629,  0.1029,  0.7095],
        [-0.2023, -1.9241,  0.6671],
        [-0.7045, -1.5642,  1.9029]])
tensor([[3, 5, 4],
        [6, 1, 9],
        [8, 8, 3]])


In [55]:
w = torch.empty(3,3, dtype=torch.float64, device='cpu') # 创建一个3行3列的矩阵，元素值随机 // dtype指定数据类型 device指定设备
print(w)


tensor([[4.9407e-324,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]], dtype=torch.float64)


In [56]:
x = torch.empty(5, 3, dtype=torch.float64, device=torch.device('cpu'), requires_grad=True) # 创建一个5行3列的矩阵，元素值随机 // dtype指定数据类型 device指定设备 requires_grad指定是否需要计算梯度
print(x)

tensor([[1.2709e-311,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]], dtype=torch.float64,
       requires_grad=True)


In [57]:
x = torch.empty_like(w) # 创建一个和w相同形状的tensor, 但数据未初始化，相当于copy但是没有黏贴
print(x)


tensor([[1.2709e-311, 4.9407e-324, 4.9407e-324],
        [4.9407e-324, 4.9407e-324, 4.9407e-324],
        [4.9407e-324, 4.9407e-324, 4.9407e-324]], dtype=torch.float64)
